version: '3.5'

services:
    backend:
        image: ml-kurkkumopo-backend
        ports:
          - 5000:5000
        volumes:
          - model:src/model

    frontend:
        image: ml-kurkkumopo-frontend
        ports:
          - 3000:3000

    training:
        image: ml-kurkkumopo-training
        volumes:
          - imgs:src/imgs
          - model:src/model

volumes:
    imgs:
    model:
