FROM ubuntu:16.04
WORKDIR /frontend-example-docker
EXPOSE 5000
RUN apt-get update && apt-get install -y curl npm nodejs git
RUN curl -sL https://deb.nodesource.com/setup_10.x | bash
RUN git clone https://github.com/docker-hy/frontend-example-docker.git
RUN npm install
CMD API_URL=http://localhost:8000 npm start
